---
- name: configure local machine for me
  hosts: local
  remote_user: samueldc
  become: yes
  vars_prompt:
    
    - name: ponto_redecamara
      prompt: Ponto RedeCamara
      private: no
    
    - name: password_redecamara
      prompt: Password Redecamara

  tasks:
  
  - name: ensure vim is installed
    ansible.builtin.apt:
      name: vim
      state: present
  
  - name: mkdir /mnt/nas
    ansible.builtin.file:
      path: /mnt/nas
      state: directory

  - name: mount my nas
    ansible.posix.mount:
      src: 192.168.1.253:/Dados
      path: /mnt/nas
      fstype: nfs
      opts: user,rw,auto,vers=3,local_lock=all,_netdev
      state: mounted
  
  - name: install davfs2
    ansible.builtin.apt:
      name: davfs2
      state: present

  - name: mkdir /mnt/nextcloud-camara
    ansible.builtin.file:
      path: /mnt/nextcloud-camara
      state: directory
      mode: '0775'
      owner: samueldc
      group: samueldc

  - name: mkdir /home/samueldc/.davfs2
    ansible.builtin.file:
      path: /home/samueldc/.davfs2
      state: directory
      mode: '0770'
      owner: samueldc
      group: samueldc

  - name: cp  /etc/davfs2/secrets /home/samueldc/.davfs2/secrets
    ansible.builtin.copy:
      src: /etc/davfs2/secrets
      remote_src: yes
      dest: /home/samueldc/.davfs2/secrets
      owner: samueldc
      group: samueldc
      mode: '0600'

  - name: edit secrets file
    ansible.builtin.lineinfile:
      path: /home/samueldc/.davfs2/secrets
      line: 'https://drive.camara.leg.br/remote.php/webdav/ {{ ponto_redecamara }} {{ password_redecamara }}'
      insertafter: EOF
      state: present

  - name: edit /etc/davfs2/davfs2.conf and add use_locks 0
    ansible.builtin.lineinfile:
      path: /etc/davfs2/davfs2.conf
      line: use_locks 0
      insertafter: EOF
      state: present

  - name: configure davfs2 group
    ansible.builtin.user:
      append: yes
      groups: davfs2
      name: samueldc
      state: present

  - name: fstab my webdav nextcloud
    ansible.posix.mount:
      src: https://drive.camara.leg.br/remote.php/webdav/
      path: /mnt/nextcloud-camara
      fstype: davfs
      opts: user,rw,auto,_netdev
      state: present

  - name: mount my webdav nextcloud
    become: yes
    become_user: samueldc
    ansible.builtin.command: 
      cmd: mount /mnt/nextcloud-camara
      creates: /mnt/nextcloud-camara/.ansible-created
      warn: no

  - name: install rawtherapee
    ansible.builtin.apt: 
      name: rawtherapee
      state: present

  - name: install steam
    ansible.builtin.apt:
      name: steam
      state: present

  - name: install google chrome
    ansible.builtin.apt:
      deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

  - name: install virtual machine manager
    ansible.builtin.apt:
      name: virt-manager
      state: present
