---
- name: configure local machine for me
  hosts: localhost
  connection: local
  gather_facts: yes
  vars: 
    ansible_python_interpreter: /usr/bin/python3
  remote_user: "{{ username }}"
  become: yes

  vars_prompt:
    
    - name: webdav_user
      prompt: Webdav user
      private: no
    
    - name: webdav_password
      prompt: Webdav password

  tasks:
  
  - name: assert Ubuntu 25.10+
    assert:
      that:
        - ansible_facts['distribution'] == "Ubuntu"
        - ansible_facts['distribution_version'] is version('25.10', '>=')
      fail_msg: "This playbook targets Ubuntu 25.10 or newer."

  - name: update apt cache
    apt:
      update_cache: yes

  - name: ensure vim is installed
    apt:
      name: vim
      state: present
  
  - name: ensure curl is installed
    apt:
      name: curl
      state: present
  
  - name: mkdir /mnt/nas
    file:
      path: /mnt/nas
      state: directory

  - name: ensure nfs client is installed
    apt:
      name: nfs-common
      state: present
  
  - name: mount my nas
    mount:
      src: 192.168.1.252:/Dados
      path: /mnt/nas
      fstype: nfs
      opts: user,rw,exec,auto,vers=3,local_lock=all,_netdev
      state: mounted
  
  - name: install davfs2
    apt:
      name: davfs2
      state: present

  - name: find mount.davfs
    command: which mount.davfs
    register: mount_davfs
    failed_when: false

  - name: setuid for davfs if present
    file:
      path: "{{ mount_davfs.stdout }}"
      mode: u+s
    when: mount_davfs.stdout != ""

  - name: mkdir /mnt/nextcloud-camara
    file:
      path: /mnt/nextcloud-camara
      state: directory
      mode: '0775'
      owner: "{{ username }}"
      group: "{{ username }}"

  - name: creates davfs2 user configuration folder
    file:
      path: "/home/{{ username }}/.davfs2"
      state: directory
      mode: '0770'
      owner: "{{ username }}"
      group: "{{ username }}"

  - name: ensure davfs2 secrets file exists with secure perms
    file:
      path: "/home/{{ username }}/.davfs2/secrets"
      state: touch
      owner: "{{ username }}"
      group: "{{ username }}"
      mode: '0600'

  - name: ensure davfs2 secret entry is present
    lineinfile:
      path: "/home/{{ username }}/.davfs2/secrets"
      line: "https://drive.camara.leg.br/remote.php/dav/files/779709D6-FF20-4EDB-993E-C5E9FA3B341A/ {{ webdav_user }} {{ webdav_password }}"
      create: yes
      insertafter: EOF
      owner: "{{ username }}"
      group: "{{ username }}"
      mode: '0600'
      state: present

  - name: edit /etc/davfs2/davfs2.conf and add use_locks 0
    lineinfile:
      path: /etc/davfs2/davfs2.conf
      line: use_locks 0
      insertafter: EOF
      state: present

  - name: configure davfs2 group
    user:
      append: yes
      groups: davfs2
      name: "{{ username }}"
      state: present

  - name: fstab my webdav nextcloud
    mount:
      # src: https://drive.camara.leg.br/remote.php/webdav/
      src: https://drive.camara.leg.br/remote.php/dav/files/779709D6-FF20-4EDB-993E-C5E9FA3B341A/
      path: /mnt/nextcloud-camara
      fstype: davfs
      opts: "user,rw,auto,uid={{ username }},_netdev,x-systemd.automount"
      state: present

#  - name: mount my webdav nextcloud
#    become: yes
#    become_user: "{{ username }}"
#    command: 
#      cmd: mount /mnt/nextcloud-camara
#      creates: /mnt/nextcloud-camara/.ansible-created
#      warn: no
#
  - name: install rawtherapee
    apt: 
      name: rawtherapee
      state: present

  - name: install inkscape
    apt: 
      name: inkscape
      state: present

  - name: install gimp
    apt: 
      name: gimp
      state: present

  - name: install steam
    apt:
      name: steam
      state: present
      ignore_errors: yes

  - name: install google chrome
    apt:
      deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

  - name: install zoom
    apt:
      deb:  https://zoom.us/client/latest/zoom_amd64.deb

  - name: install notepadqq
    apt:
      name: notepadqq
      state: present
      ignore_errors: yes

  - name: add microsoft key
    apt_key:
      url: https://packages.microsoft.com/keys/microsoft.asc
      keyring: /etc/apt/trusted.gpg.d/packages.microsoft.gpg
      state: present

  - name: update apt cache
    apt:
      update_cache: yes

  - name: add microsoft repo
    apt_repository:
      repo: deb [arch=amd64] https://packages.microsoft.com/repos/code stable main
      state: present

  - name: install vscode
    apt:
      name: code
      state: present

  - name: install zsh
    apt: 
      name: zsh
      state: present

  - name: return zsh path
    shell: which zsh
    register: zsh_path
    check_mode: no

  - name: configure zsh user shell
    user:
      name: "{{ username }}"
      state: present
      shell: "{{ zsh_path.stdout }}"

  - name: populate .zshrc with recommended settings
    copy:
      src: /etc/zsh/newuser.zshrc.recommended
      remote_src: yes
      dest: "/home/{{ username }}/.zshrc"
      owner: "{{ username }}"
      group: "{{ username }}"
      mode: '0600'

  - name: install oh-my-zsh
    become: yes
    become_user: "{{ username }}"
    shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    args:
      creates: "/home/{{ username }}/.oh-my-zsh/oh-my-zsh.sh"

  - name: install zsh extras
    apt: 
      name: fonts-powerline
      state: present

  - name: create temporary firacode directory
    tempfile:
      state: directory
      suffix: firacode
    register: firacode_dir
    check_mode: no

  - name: download and extract firacode fonts
    unarchive: 
      src: https://github.com/tonsky/FiraCode/releases/download/5.2/Fira_Code_v5.2.zip
      dest: {{ firacode_dir.path }}
      remote_src: yes
      extra_opts: 
      - --one-top-level=firacode
      - --strip-components=1

  - name: install firacode fonts
    copy:
      src: "{{ firacode_dir.path }}/ttf/"
      dest: /usr/local/share/fonts/firacode/
      remote_src: yes
      state: link

  - name: rebuild font cache
    command: fc-cache -f -v
    args:
      warn: false
    when: ansible_facts['os_family'] == 'Debian'

  - name: install spaceship prompt
    become: yes
    become_user: "{{ username }}"
    shell: "git clone https://github.com/denysdovhan/spaceship-prompt.git /home/{{ username }}/.oh-my-zsh/custom/themes/spaceship-prompt"
    args:
      creates: "/home/{{ username }}/.oh-my-zsh/custom/themes/spaceship-prompt/spaceship.zsh-theme"

  - name: configure spaceship theme symlink
    become: yes
    become_user: "{{ username }}"
    shell: "ln -s /home/{{ username }}/.oh-my-zsh/custom/themes/spaceship-prompt/spaceship.zsh-theme /home/{{ username }}/.oh-my-zsh/custom/themes/spaceship.zsh-theme"
    args:
      creates: "/home/{{ username }}/.oh-my-zsh/themes/spaceship.zsh-theme"

  - name: configure spaceship theme
    lineinfile:
      path: "/home/{{ username }}/.zshrc"
      regexp: '^ZSH_THEME=.*$'
      line: 'ZSH_THEME="spaceship"'
      state: present

  - name: configure spaceship preferences
    blockinfile:
      path: "/home/{{ username }}/.zshrc"
      marker: "# {mark} SPACESHIP PREFERENCES"
      insertafter: EOF
      block: |
        SPACESHIP_PROMPT_ORDER=(
          user          # Username section
          dir           # Current directory section
          host          # Hostname section
          git           # Git section (git_branch + git_status)
          hg            # Mercurial section (hg_branch  + hg_status)
          exec_time     # Execution time
          line_sep      # Line break
          vi_mode       # Vi-mode indicator
          jobs          # Background jobs indicator
          exit_code     # Exit code section
          char          # Prompt character
        )
        SPACESHIP_USER_SHOW=always
        SPACESHIP_PROMPT_ADD_NEWLINE=true
        # SPACESHIP_CHAR_SYMBOL="â¯"
        SPACESHIP_CHAR_SUFFIX=" "

  - name: install zinit
    become: yes
    become_user: "{{ username }}"
    shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/zdharma/zinit/master/doc/install.sh)"
    when: "'Added by Zinit' not in lookup('file', '/home/{{ username }}/.zshrc')"

  - name: install zinit plugins
    blockinfile:
      path: "/home/{{ username }}/.zshrc"
      marker: "# {mark} ZINIT PLUGINS"
      insertafter: EOF
      block: |
        zinit light zdharma/fast-syntax-highlighting
        zinit light zsh-users/zsh-autosuggestions
        zinit light zsh-users/zsh-completions

  - name: compile zinit ???
    become: yes
    become_user: "{{ username }}"
    shell: zinit self-update
    args:
      creates: "/home/{{ username }}/.zinit/completions"

  - name: configure xhost for gparted
    lineinfile:
      path: "/home/{{ username }}/.zshrc"
      line: "xhost +local: > /dev/null"
      insertafter: EOF
      state: present

  - name: configure webdav for mounting
    blockinfile:
      path: "/home/{{ username }}/.config/autostart/mount.desktop"
      marker: "# {mark} MOUNT WEBDAV"
      insertafter: EOF
      create: yes
      block: |
        [Desktop Entry]
        Type=Application
        Exec=mount /mnt/nextcloud-camara
        Hidden=false
        NoDisplay=false
        X-GNOME-Autostart-enabled=true
        Name[en_US]=Mount WebDav
        Name=Mount WebDav
        Comment[en_US]=
        Comment=

# - name: configure vscode settings for zsh

  - name: configure function keys to work only when fn is pressed
    lineinfile:
      path: /etc/modprobe.d/hid_apple.conf
      line: options hid_apple fnmode=2
      insertafter: EOF
      state: present
      create: yes
    register: result_fn

  - name: configure bluetooth module to work with xbox on controller
    lineinfile:
      path: /etc/modprobe.d/xbox-one-controller.conf
      line: options bluetooth disable_ertm=1
      insertafter: EOF
      state: present
      create: yes
    register: result_xbox

  - name: reload kernel modules
    shell: update-initramfs -u -k all
    when: result_fn.changed or result_xbox.changed

  - name: configure cedilla
    lineinfile:
      path: /etc/environment
      line: GTK_IM_MODULE=cedilla
      insertafter: EOF
      state: present

  - name: install video4linux utilities
    apt: 
      name: v4l-utils
      state: present

  - name: configure udev rules for logitech c922 webcam
    blockinfile:
      path: /etc/udev/rules.d/98-logitech-c922.rules
      mode: '0644'
      marker: "# {mark} UDEV RULES FOR WEBCAM"
      insertafter: EOF
      create: yes
      block: |
        SUBSYSTEM=="video4linux", KERNEL=="video[0-9]*", ATTRS{product}=="C922 Pro Stream Webcam", ATTR{index}=="0", RUN+="/usr/bin/v4l2-ctl -d $devnode --set-ctrl white_balance_temperature_auto=0"
        SUBSYSTEM=="video4linux", KERNEL=="video[0-9]*", ATTRS{product}=="C922 Pro Stream Webcam", ATTR{index}=="0", RUN+="/usr/bin/v4l2-ctl -d $devnode --set-ctrl exposure_auto=1"
    register: result_udev

  - name: configure udev rules for logitech c922 webcam part 2
    blockinfile:
      path: /etc/udev/rules.d/99-logitech-c922.rules
      mode: '0644'
      marker: "# {mark} UDEV RULES FOR WEBCAM PART 2"
      insertafter: EOF
      create: yes
      block: |
        SUBSYSTEM=="video4linux", KERNEL=="video[0-9]*", ATTRS{product}=="C922 Pro Stream Webcam", ATTR{index}=="0", RUN+="/usr/bin/v4l2-ctl -d $devnode --set-ctrl exposure_absolute=600"
        SUBSYSTEM=="video4linux", KERNEL=="video[0-9]*", ATTRS{product}=="C922 Pro Stream Webcam", ATTR{index}=="0", RUN+="/usr/bin/v4l2-ctl -d $devnode --set-ctrl white_balance_temperature=2000"
    register: result_udev

  - name: reload udev rules
    shell: udevadm control --reload
    when: result_udev.changed

  - name find udevadm command
    command: which udevadm
    register: udevadm_path
    failed_when: false

  - name: trigger webcam udev rules
    shell: udevadm trigger --name-match=/dev/video0
    become: yes
    when: udevadm_path.stdout != ""

  - name: configure to trigger webcam udev rules at startup
    blockinfile:
      path: "/home/{{ username }}/.config/autostart/trigger-webcam-udev-rules.desktop"
      marker: "# {mark} TRIGGER WEBCAM UDEV RULES"
      insertafter: EOF
      create: yes
      block: |
        [Desktop Entry]
        Type=Application
        Exec=udevadm trigger --name-match=/dev/video0
        Hidden=false
        NoDisplay=false
        X-GNOME-Autostart-enabled=true
        Name[en_US]=Trigger Webcam Udev Rules
        Name=Trigger Webcam Udev Rules
        Comment[en_US]=
        Comment=

  - name: install pksc11 dependencies
    apt: 
      name: 
      - libjbig0
      - libtiff5
      - fontconfig-config
      - libfontconfig1
      - libwxbase3.0-0v5
      - libwxgtk3.0-gtk3-0v5
      - libpcsclite1
      - libccid
      - pcscd
      - libnss3
      - libnss3-tools
      state: present

  - name: create temporary safenet directory
    tempfile:
      state: directory
      suffix: safenet
    register: safenet_dir
    check_mode: no

  - name: download and extract safenet client
    unarchive:
      src: http://repositorio.serpro.gov.br/drivers/safenet/linux/SafenetAuthenticationClient-BR-10.3_Linux_Ubuntu-RedHat(32-64bits).zip
      dest: "{{ safenet_dir.path }}"
      remote_src: yes

  - name: install safenet client
    apt:
      deb: "{{ safenet_dir.path }}/SafenetAuthenticationClient-BR-10.0.37-0_amd64.deb"
  - name: find libcrypto
    shell: ls /usr/lib/x86_64-linux-gnu/libcrypto.so.* || true
    register: libcrypto_files
    failed_when: false
    changed_when: false

  - name: create symlink for safenet if needed
    file:
      src: "{{ libcrypto_files.stdout_lines[-1] }}"
      dest: /usr/lib/libcrypto.so.6
      state: link
    when: libcrypto_files.stdout_lines is defined and libcrypto_files.stdout_lines | length > 0 and '/usr/lib/libcrypto.so.6' not in libcrypto_files.stdout_lines

  - name: verify pkcs11 for chrome
    become: yes
    become_user: "{{ username }}"
    shell: modutil -dbdir sql:/home/{{ username }}/.pki/nssdb/ -list | grep "Safenet Token"
    register: result_pkcs11
    ignore_errors: true
    check_mode: no

  - name: configure pkcs11 for chrome
    become: yes
    become_user: "{{ username }}"
    shell: modutil -dbdir sql:/home/{{ username }}/.pki/nssdb/ -add "Safenet Token" -libfile /usr/lib/libeToken.so
    when: "'Safenet Token' not in result_pkcs11.stdout"

  - name: install qemu kvm
    apt:
      name:
      - qemu
      - libvirt-daemon-system
      - libvirt-clients
      - bridge-utils
      - virt-manager
      - libvirt-dev
      state: present

  - name: add user to qemu kvm groups
    user:
      append: yes
      groups: 
      - libvirt
      - kvm
      name: "{{ username }}"
      state: present
